# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Username=administrator@localhost
@Password=Administrator1!
@BearerToken=1234

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}"
}

###

# POST Game CreateNewGame
POST {{Web_HostAddress}}/api/Game/CreatNewGame
Content-Type: application/json

{
  "username": "{{Username}}",
}

###


# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}
