# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Username=administrator@localhost
@Password=Administrator1!
@BearerToken=1234

# POST Game CreateNewGame
POST {{Web_HostAddress}}/api/Game/CreatNewGame
Content-Type: application/json

{
  
}

###

